name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # Commenter ou supprimer cette section si vous n'avez pas de requirements.txt
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run bot
        env:
          DISCORD_BOT_TOKEN: ${{ secrets.TOKENBOTDISCORD }}
        run: |
          python main.py

